from typing import List

# =========================================
# --- Matrix Traversal
# =========================================

def dfs_traversal():...
def bfs_traversal():...
def diagonal_traversal():...
def spiral_traversal():...

# =========================================
# --- Matrix Manipulation
# =========================================

def rotate_90_degrees_clockwise():...
def transpose_matrix():...
def set_matrix_zeroes():...

# =========================================
# --- Searching in a Matrix
# =========================================

def search_in_2d_matrix():...